### ISSUE TITLE
Rename parameterless From method

### ISSUE THREAD

**Issue by blairconrad** [blairconrad/MakeItEasy#7]
As @thomaslevesque notes, `Make.A<Thing>().From()` reads a little weird.

Alternatives we've been kicking around:

* `Make.A<Pizza>().Please()` (Please was part of @blairconrad's original API, and he's partial to it)
* `Make.A<Pizza>().WithDefaults()`
* `Make.Any<Pizza>()` (but what if it has _neither_ ham nor pineapple?)
* `Make.ASimple<Pizza>()`
* `Make.A<Pizza>().FromNothing()`
* `Make.A<Pizza>().OutOfTheFormlessVoidThroughSheerForceOfWill()`

We could always leave the parameterless `From` and just add an alternative, of course.

**Comment by thomaslevesque** [comment]
I think my favorite options are `.FromNothing()` (for consistency with `From`) and `.WithDefaults()` (because it best describes what it does). But if you decide to go with `.Please()`, that's fine too!

**Comment by blairconrad** [comment]
Renamed to `FromDefaults`, and released in [version 0.2.0](https://github.com/blairconrad/MakeItEasy/releases/tag/0.2.0).
